CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" text NOT NULL,
  "role" integer NOT NULL DEFAULT -1 REFERENCES "roles" ("id") ON DELETE SET DEFAULT ON UPDATE CASCADE
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL
);

COMMENT ON COLUMN "roles"."name" IS 'Role name';

CREATE TABLE "log_actions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(255) NOT NULL,
  "description" text NOT NULL,
  "user_id" integer NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON COLUMN "log_actions"."type" IS 'Type of action';

CREATE TABLE "patients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "birthday" date NOT NULL,
  "user_id" integer NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "doctors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "qualification" integer NOT NULL DEFAULT 2,
  "user_id" integer NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "specialization_id" integer NOT NULL DEFAULT -1 REFERENCES "specializations" ("id") ON DELETE SET DEFAULT ON UPDATE CASCADE
);

COMMENT ON COLUMN "doctors"."qualification" IS '2 - second category(x1.2)\n1 - first category(x1.5)\n0 - the highest category(x2)';

CREATE TABLE "specializations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" text NOT NULL,
  "service_fee" decimal(19,2) NOT NULL DEFAULT 0
);

COMMENT ON COLUMN "specializations"."name" IS 'Spec name';

CREATE TABLE "medications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" text NOT NULL,
  "price" decimal(19,2) NOT NULL DEFAULT 0
);

COMMENT ON COLUMN "medications"."name" IS 'Medication name';

CREATE TABLE "prescriptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dosage" decimal(6,2) NOT NULL,
  "issue_date" date NOT NULL DEFAULT (current_date),
  "medication_id" integer NOT NULL DEFAULT -1 REFERENCES "medications" ("id") ON DELETE SET DEFAULT ON UPDATE CASCADE,
  "medical_record_id" integer NOT NULL DEFAULT -1 REFERENCES "medical_records" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON COLUMN "prescriptions"."dosage" IS 'Dosage in mg';

CREATE TABLE "medical_records" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "diagnosis" text NOT NULL,
  "conclusion_date" date NOT NULL DEFAULT (current_date),
  "doctor_id" integer NOT NULL DEFAULT -1 REFERENCES "doctors" ("id") ON DELETE SET DEFAULT ON UPDATE CASCADE,
  "patient_id" integer NOT NULL DEFAULT -1 REFERENCES "patients" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "appointments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" timestamp NOT NULL,
  "status" varchar(1) NOT NULL DEFAULT '0',
  "doctor_id" integer NOT NULL DEFAULT -1 REFERENCES "doctors" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "patient_id" integer NOT NULL DEFAULT -1 REFERENCES "patients" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON COLUMN "appointments"."status" IS '0 - active\n1 - passed\n2 - canceled by client\n3 - canceled by clinic';

CREATE TABLE "doctors_schedules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "skip_days" varchar(255) NOT NULL DEFAULT '6,7',
  "work_time" varchar(255) NOT NULL DEFAULT '8-16',
  "doctor_id" integer NOT NULL REFERENCES "doctors" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON COLUMN "doctors_schedules"."skip_days" IS 'Days when not at work (Saturday, Sunday - default)';
COMMENT ON COLUMN "doctors_schedules"."work_time" IS 'Work time, default: 8:00 - 16:00';

CREATE TABLE "bills" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" decimal(19,2) NOT NULL,
  "invoice_date" date NOT NULL DEFAULT (current_date),
  "payment_status" varchar(1) NOT NULL DEFAULT '0',
  "patient_id" integer NOT NULL REFERENCES "patients" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON COLUMN "bills"."payment_status" IS '0 - not paid\n1 - paid';
